version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: courier_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  app1:
    build: .
    environment:
      DATABASE_URL: mysql+mysqlconnector://user:password@db/courier_db
      PROCESS_URL: http://processor:8080
      SERVICE_NAME: app1
      SERVICE_PORT: 8001
    ports:
      - "8001:8000"
    depends_on:
      - db
      - processor
    networks:
      - mynetwork

  app2:
    build: .
    environment:
      DATABASE_URL: mysql+mysqlconnector://user:password@db/courier_db
      PROCESS_URL: http://processor:8080
      SERVICE_NAME: app2
      SERVICE_PORT: 8002
    ports:
      - "8002:8000"
    depends_on:
      - db
      - processor
    networks:
      - mynetwork

  app3:
    build: .
    environment:
      DATABASE_URL: mysql+mysqlconnector://user:password@db/courier_db
      PROCESS_URL: http://processor:8080
      SERVICE_NAME: app3
      SERVICE_PORT: 8003
    ports:
      - "8003:8000"
    depends_on:
      - db
      - processor
    networks:
      - mynetwork

  processor:
    image: igorsakhankov/harbour-cloudcomputing
    ports:
      - "8181:8080"
    networks:
      - mynetwork

  load_balancer:
    build: ./load_balancer
    ports:
      - "8000:8000"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
